CREATE DOMAIN isbn AS VARCHAR CHECK(VALUE ~ '^(978|979)[0-9]{6,6}([0-9X]|[0-9]{4,4})$');

CREATE DOMAIN issn AS CHAR(9) CHECK(VALUE ~ '[0-9]{4}-[0-9]{3}([0-9]|X)');

CREATE DOMAIN doi AS VARCHAR CHECK(VALUE !~ '^10.[0-9]*$');

CREATE DOMAIN email_type AS VARCHAR CHECK (VALUE LIKE '%@%.%');